# Generated by apidoc - http://www.apidoc.me
# Service version: 0.0.31
# apidoc:0.11.28 http://www.apidoc.me/flow/catalog/0.0.31/ruby_client

require 'cgi'
require 'net/http'
require 'net/https'
require 'uri'
require 'base64'

require 'date'
require 'rubygems'
require 'json'
require 'bigdecimal'

# API to the product catalog, defining the master catalog and all of the
# subcatalogs used to target specific subsets of the inventory to experiences.
module Io
  module Flow
    module Catalog
      module V0

        class Client

          module Constants

            BASE_URL = 'https://catalog.api.flow.io' unless defined?(Constants::BASE_URL)
            NAMESPACE = 'io.flow.catalog.v0' unless defined?(Constants::NAMESPACE)
            USER_AGENT = 'apidoc:0.11.28 http://www.apidoc.me/flow/catalog/0.0.31/ruby_client' unless defined?(Constants::USER_AGENT)
            VERSION = '0.0.31' unless defined?(Constants::VERSION)
            VERSION_MAJOR = 0 unless defined?(VERSION_MAJOR)

          end

          attr_reader :url

          def initialize(url, opts={})
            @url = HttpClient::Preconditions.assert_class('url', url, String)
            @authorization = HttpClient::Preconditions.assert_class_or_nil('authorization', opts.delete(:authorization), HttpClient::Authorization)
            @default_headers = HttpClient::Preconditions.assert_class('default_headers', opts.delete(:default_headers) || {}, Hash)
            HttpClient::Preconditions.assert_empty_opts(opts)
            HttpClient::Preconditions.check_state(url.match(/http.+/i), "URL[%s] must start with http" % url)
          end

          # Creates an instance of the client using the base url specified in the API spec.
          def Client.at_base_url(opts={})
            Client.new(Constants::BASE_URL, opts)
          end

          def request(path=nil)
            HttpClient::Preconditions.assert_class_or_nil('path', path, String)
            request = HttpClient::Request.new(URI.parse(@url + path.to_s)).with_header('User-Agent', Constants::USER_AGENT).with_header('X-Apidoc-Version', Constants::VERSION).with_header('X-Apidoc-Version-Major', Constants::VERSION_MAJOR)

            @default_headers.each do |key, value|
              request = request.with_header(key, value)
            end

            if @authorization
              request = request.with_auth(@authorization)
            end

            request
          end

          def catalogs
            @catalogs ||= ::Io::Flow::Catalog::V0::Clients::Catalogs.new(self)
          end

          def functions
            @functions ||= ::Io::Flow::Catalog::V0::Clients::Functions.new(self)
          end

          def items
            @items ||= ::Io::Flow::Catalog::V0::Clients::Items.new(self)
          end

          def subcatalogs
            @subcatalogs ||= ::Io::Flow::Catalog::V0::Clients::Subcatalogs.new(self)
          end

          def subcatalog_items
            @subcatalog_items ||= ::Io::Flow::Catalog::V0::Clients::SubcatalogItems.new(self)
          end
        end

        module Clients

          class Catalogs

            def initialize(client)
              @client = HttpClient::Preconditions.assert_class('client', client, ::Io::Flow::Catalog::V0::Client)
            end

            # Returns information about a specific catalog.
            def get_catalog(organization)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              r = @client.request("/#{CGI.escape(organization)}/catalog").get
              ::Io::Flow::Catalog::V0::Models::Catalog.new(r)
            end

          end

          class Functions

            def initialize(client)
              @client = HttpClient::Preconditions.assert_class('client', client, ::Io::Flow::Catalog::V0::Client)
            end

            # Provides visibility into recent changes of each object, including deletion
            def get_versions(organization, incoming={})
              HttpClient::Preconditions.assert_class('organization', organization, String)
              opts = HttpClient::Helper.symbolize_keys(incoming)
              query = {
                :id => (x = opts.delete(:id); x.nil? ? nil : HttpClient::Preconditions.assert_class('id', x, Array).map { |v| HttpClient::Preconditions.assert_class('id', v, String) }),
                :name => (x = opts.delete(:name); x.nil? ? nil : HttpClient::Preconditions.assert_class('name', x, Array).map { |v| HttpClient::Preconditions.assert_class('name', v, String) }),
                :limit => HttpClient::Preconditions.assert_class('limit', (x = opts.delete(:limit); x.nil? ? 25 : x), Integer),
                :offset => HttpClient::Preconditions.assert_class('offset', (x = opts.delete(:offset); x.nil? ? 0 : x), Integer),
                :sort => HttpClient::Preconditions.assert_class('sort', (x = opts.delete(:sort); x.nil? ? "journal_timestamp" : x), String)
              }.delete_if { |k, v| v.nil? }
              r = @client.request("/#{CGI.escape(organization)}/functions/versions").with_query(query).get
              r.map { |x| ::Io::Flow::Catalog::V0::Models::FunctionVersion.new(x) }
            end

            # Search functions. Always paginated.
            def get(organization, incoming={})
              HttpClient::Preconditions.assert_class('organization', organization, String)
              opts = HttpClient::Helper.symbolize_keys(incoming)
              query = {
                :id => (x = opts.delete(:id); x.nil? ? nil : HttpClient::Preconditions.assert_class('id', x, Array).map { |v| HttpClient::Preconditions.assert_class('id', v, String) }),
                :name => (x = opts.delete(:name); x.nil? ? nil : HttpClient::Preconditions.assert_class('name', x, Array).map { |v| HttpClient::Preconditions.assert_class('name', v, String) }),
                :position => (x = opts.delete(:position); x.nil? ? nil : HttpClient::Preconditions.assert_class('position', x, Array).map { |v| HttpClient::Preconditions.assert_class('position', v, Integer) }),
                :subcatalog => (x = opts.delete(:subcatalog); x.nil? ? nil : HttpClient::Preconditions.assert_class('subcatalog', x, Array).map { |v| HttpClient::Preconditions.assert_class('subcatalog', v, String) }),
                :limit => HttpClient::Preconditions.assert_class('limit', (x = opts.delete(:limit); x.nil? ? 25 : x), Integer),
                :offset => HttpClient::Preconditions.assert_class('offset', (x = opts.delete(:offset); x.nil? ? 0 : x), Integer),
                :sort => HttpClient::Preconditions.assert_class('sort', (x = opts.delete(:sort); x.nil? ? "name" : x), String)
              }.delete_if { |k, v| v.nil? }
              r = @client.request("/#{CGI.escape(organization)}/functions").with_query(query).get
              r.map { |x| ::Io::Flow::Catalog::V0::Models::Function.new(x) }
            end

            # Returns information about a specific function.
            def get_by_id(organization, id)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('id', id, String)
              r = @client.request("/#{CGI.escape(organization)}/functions/#{CGI.escape(id)}").get
              ::Io::Flow::Catalog::V0::Models::Function.new(r)
            end

            # Add function
            def post(organization, function_form)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('function_form', function_form, ::Io::Flow::Catalog::V0::Models::FunctionForm)
              r = @client.request("/#{CGI.escape(organization)}/functions").with_json(function_form.to_json).post
              ::Io::Flow::Catalog::V0::Models::Function.new(r)
            end

            # Update function with the specified id, creating if it does not exist.
            def put_by_id(organization, id, function_form)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('id', id, String)
              HttpClient::Preconditions.assert_class('function_form', function_form, ::Io::Flow::Catalog::V0::Models::FunctionForm)
              r = @client.request("/#{CGI.escape(organization)}/functions/#{CGI.escape(id)}").with_json(function_form.to_json).put
              ::Io::Flow::Catalog::V0::Models::Function.new(r)
            end

            # Delete the function with this id
            def delete_by_id(organization, id)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('id', id, String)
              r = @client.request("/#{CGI.escape(organization)}/functions/#{CGI.escape(id)}").delete
              nil
            end

          end

          class Items

            def initialize(client)
              @client = HttpClient::Preconditions.assert_class('client', client, ::Io::Flow::Catalog::V0::Client)
            end

            # Provides visibility into recent changes of each object, including deletion
            def get_versions(organization, incoming={})
              HttpClient::Preconditions.assert_class('organization', organization, String)
              opts = HttpClient::Helper.symbolize_keys(incoming)
              query = {
                :id => (x = opts.delete(:id); x.nil? ? nil : HttpClient::Preconditions.assert_class('id', x, Array).map { |v| HttpClient::Preconditions.assert_class('id', v, String) }),
                :number => (x = opts.delete(:number); x.nil? ? nil : HttpClient::Preconditions.assert_class('number', x, Array).map { |v| HttpClient::Preconditions.assert_class('number', v, String) }),
                :limit => HttpClient::Preconditions.assert_class('limit', (x = opts.delete(:limit); x.nil? ? 25 : x), Integer),
                :offset => HttpClient::Preconditions.assert_class('offset', (x = opts.delete(:offset); x.nil? ? 0 : x), Integer),
                :sort => HttpClient::Preconditions.assert_class('sort', (x = opts.delete(:sort); x.nil? ? "journal_timestamp" : x), String)
              }.delete_if { |k, v| v.nil? }
              r = @client.request("/#{CGI.escape(organization)}/catalog/items/versions").with_query(query).get
              r.map { |x| ::Io::Flow::Catalog::V0::Models::ItemVersion.new(x) }
            end

            # Search items. Always paginated.
            def get(organization, incoming={})
              HttpClient::Preconditions.assert_class('organization', organization, String)
              opts = HttpClient::Helper.symbolize_keys(incoming)
              query = {
                :id => (x = opts.delete(:id); x.nil? ? nil : HttpClient::Preconditions.assert_class('id', x, Array).map { |v| HttpClient::Preconditions.assert_class('id', v, String) }),
                :number => (x = opts.delete(:number); x.nil? ? nil : HttpClient::Preconditions.assert_class('number', x, Array).map { |v| HttpClient::Preconditions.assert_class('number', v, String) }),
                :query => (x = opts.delete(:query); x.nil? ? nil : HttpClient::Preconditions.assert_class('query', x, String)),
                :limit => HttpClient::Preconditions.assert_class('limit', (x = opts.delete(:limit); x.nil? ? 25 : x), Integer),
                :offset => HttpClient::Preconditions.assert_class('offset', (x = opts.delete(:offset); x.nil? ? 0 : x), Integer),
                :sort => HttpClient::Preconditions.assert_class('sort', (x = opts.delete(:sort); x.nil? ? "name" : x), String)
              }.delete_if { |k, v| v.nil? }
              r = @client.request("/#{CGI.escape(organization)}/catalog/items").with_query(query).get
              r.map { |x| ::Io::Flow::Catalog::V0::Models::Item.new(x) }
            end

            # Returns information about a specific item.
            def get_by_number(organization, number)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('number', number, String)
              r = @client.request("/#{CGI.escape(organization)}/catalog/items/#{CGI.escape(number)}").get
              ::Io::Flow::Catalog::V0::Models::Item.new(r)
            end

            # Add catalog item(s)
            def post(organization, item_form)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('item_form', item_form, ::Io::Flow::Catalog::V0::Models::ItemForm)
              r = @client.request("/#{CGI.escape(organization)}/catalog/items").with_json(item_form.to_json).post
              ::Io::Flow::Catalog::V0::Models::Item.new(r)
            end

            # Update item with the specified number, creating if it does not exist.
            def put_by_number(organization, number, item_form)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('number', number, String)
              HttpClient::Preconditions.assert_class('item_form', item_form, ::Io::Flow::Catalog::V0::Models::ItemForm)
              r = @client.request("/#{CGI.escape(organization)}/catalog/items/#{CGI.escape(number)}").with_json(item_form.to_json).put
              ::Io::Flow::Catalog::V0::Models::Item.new(r)
            end

            # Delete the item with this number
            def delete_by_number(organization, number)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('number', number, String)
              r = @client.request("/#{CGI.escape(organization)}/catalog/items/#{CGI.escape(number)}").delete
              nil
            end

          end

          class Subcatalogs

            def initialize(client)
              @client = HttpClient::Preconditions.assert_class('client', client, ::Io::Flow::Catalog::V0::Client)
            end

            # Provides visibility into recent changes of each object, including deletion
            def get_versions(organization, incoming={})
              HttpClient::Preconditions.assert_class('organization', organization, String)
              opts = HttpClient::Helper.symbolize_keys(incoming)
              query = {
                :id => (x = opts.delete(:id); x.nil? ? nil : HttpClient::Preconditions.assert_class('id', x, Array).map { |v| HttpClient::Preconditions.assert_class('id', v, String) }),
                :key => (x = opts.delete(:key); x.nil? ? nil : HttpClient::Preconditions.assert_class('key', x, Array).map { |v| HttpClient::Preconditions.assert_class('key', v, String) }),
                :limit => HttpClient::Preconditions.assert_class('limit', (x = opts.delete(:limit); x.nil? ? 25 : x), Integer),
                :offset => HttpClient::Preconditions.assert_class('offset', (x = opts.delete(:offset); x.nil? ? 0 : x), Integer),
                :sort => HttpClient::Preconditions.assert_class('sort', (x = opts.delete(:sort); x.nil? ? "journal_timestamp" : x), String)
              }.delete_if { |k, v| v.nil? }
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs/versions").with_query(query).get
              r.map { |x| ::Io::Flow::Catalog::V0::Models::SubcatalogVersion.new(x) }
            end

            # Search subcatalogs. Always paginated.
            def get(organization, incoming={})
              HttpClient::Preconditions.assert_class('organization', organization, String)
              opts = HttpClient::Helper.symbolize_keys(incoming)
              query = {
                :id => (x = opts.delete(:id); x.nil? ? nil : HttpClient::Preconditions.assert_class('id', x, Array).map { |v| HttpClient::Preconditions.assert_class('id', v, String) }),
                :key => (x = opts.delete(:key); x.nil? ? nil : HttpClient::Preconditions.assert_class('key', x, Array).map { |v| HttpClient::Preconditions.assert_class('key', v, String) }),
                :limit => HttpClient::Preconditions.assert_class('limit', (x = opts.delete(:limit); x.nil? ? 25 : x), Integer),
                :offset => HttpClient::Preconditions.assert_class('offset', (x = opts.delete(:offset); x.nil? ? 0 : x), Integer),
                :sort => HttpClient::Preconditions.assert_class('sort', (x = opts.delete(:sort); x.nil? ? "-created_at" : x), String)
              }.delete_if { |k, v| v.nil? }
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs").with_query(query).get
              r.map { |x| ::Io::Flow::Catalog::V0::Models::Subcatalog.new(x) }
            end

            # Returns information about a specific subcatalog.
            def get_by_key(organization, key)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('key', key, String)
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs/#{CGI.escape(key)}").get
              ::Io::Flow::Catalog::V0::Models::Subcatalog.new(r)
            end

            # Add subcatalog
            def post(organization, subcatalog_form)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('subcatalog_form', subcatalog_form, ::Io::Flow::Catalog::V0::Models::SubcatalogForm)
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs").with_json(subcatalog_form.to_json).post
              ::Io::Flow::Catalog::V0::Models::Subcatalog.new(r)
            end

            # Update subcatalog with the specified key, creating if it does not exist.
            def put_by_key(organization, key, subcatalog_form)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('key', key, String)
              HttpClient::Preconditions.assert_class('subcatalog_form', subcatalog_form, ::Io::Flow::Catalog::V0::Models::SubcatalogForm)
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs/#{CGI.escape(key)}").with_json(subcatalog_form.to_json).put
              ::Io::Flow::Catalog::V0::Models::Subcatalog.new(r)
            end

            # Delete the subcatalog with this key
            def delete_by_key(organization, key)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('key', key, String)
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs/#{CGI.escape(key)}").delete
              nil
            end

            # Returns information about a specific subcatalog's settings.
            def get_settings_by_key(organization, key)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('key', key, String)
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs/#{CGI.escape(key)}/settings").get
              ::Io::Flow::Catalog::V0::Models::SubcatalogSettings.new(r)
            end

            # Update subcatalog settings for the specified subcatalog.
            def put_settings_by_key(organization, key, subcatalog_settings_form)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('key', key, String)
              HttpClient::Preconditions.assert_class('subcatalog_settings_form', subcatalog_settings_form, ::Io::Flow::Catalog::V0::Models::SubcatalogSettingsForm)
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs/#{CGI.escape(key)}/settings").with_json(subcatalog_settings_form.to_json).put
              ::Io::Flow::Catalog::V0::Models::SubcatalogSettings.new(r)
            end

            # Sync subcatalog
            def post_events_by_key_and_event(organization, key, event, hash)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('key', key, String)
              HttpClient::Preconditions.assert_class('event', event, String)
              HttpClient::Preconditions.assert_class('hash', hash, Hash)
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs/#{CGI.escape(key)}/events/#{CGI.escape(event)}").with_json(hash.to_json).post
              nil
            end

          end

          class SubcatalogItems

            def initialize(client)
              @client = HttpClient::Preconditions.assert_class('client', client, ::Io::Flow::Catalog::V0::Client)
            end

            # Provides visibility into recent changes of each object, including deletion
            def get_versions(organization, subcatalog, incoming={})
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('subcatalog', subcatalog, String)
              opts = HttpClient::Helper.symbolize_keys(incoming)
              query = {
                :id => (x = opts.delete(:id); x.nil? ? nil : HttpClient::Preconditions.assert_class('id', x, Array).map { |v| HttpClient::Preconditions.assert_class('id', v, String) }),
                :number => (x = opts.delete(:number); x.nil? ? nil : HttpClient::Preconditions.assert_class('number', x, Array).map { |v| HttpClient::Preconditions.assert_class('number', v, String) }),
                :limit => HttpClient::Preconditions.assert_class('limit', (x = opts.delete(:limit); x.nil? ? 25 : x), Integer),
                :offset => HttpClient::Preconditions.assert_class('offset', (x = opts.delete(:offset); x.nil? ? 0 : x), Integer),
                :sort => HttpClient::Preconditions.assert_class('sort', (x = opts.delete(:sort); x.nil? ? "journal_timestamp" : x), String)
              }.delete_if { |k, v| v.nil? }
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs/#{CGI.escape(subcatalog)}/items/versions").with_query(query).get
              r.map { |x| ::Io::Flow::Catalog::V0::Models::SubcatalogVersion.new(x) }
            end

            # Search subcatalog items. Always paginated.
            def get(organization, subcatalog, incoming={})
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('subcatalog', subcatalog, String)
              opts = HttpClient::Helper.symbolize_keys(incoming)
              query = {
                :id => (x = opts.delete(:id); x.nil? ? nil : HttpClient::Preconditions.assert_class('id', x, Array).map { |v| HttpClient::Preconditions.assert_class('id', v, String) }),
                :number => (x = opts.delete(:number); x.nil? ? nil : HttpClient::Preconditions.assert_class('number', x, Array).map { |v| HttpClient::Preconditions.assert_class('number', v, String) }),
                :query => (x = opts.delete(:query); x.nil? ? nil : HttpClient::Preconditions.assert_class('query', x, String)),
                :limit => HttpClient::Preconditions.assert_class('limit', (x = opts.delete(:limit); x.nil? ? 25 : x), Integer),
                :offset => HttpClient::Preconditions.assert_class('offset', (x = opts.delete(:offset); x.nil? ? 0 : x), Integer),
                :sort => HttpClient::Preconditions.assert_class('sort', (x = opts.delete(:sort); x.nil? ? "lower(name)" : x), String)
              }.delete_if { |k, v| v.nil? }
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs/#{CGI.escape(subcatalog)}/items").with_query(query).get
              r.map { |x| ::Io::Flow::Catalog::V0::Models::Item.new(x) }
            end

            # Returns information about specific subcatalog items.
            def get_by_number(organization, subcatalog, number)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('subcatalog', subcatalog, String)
              HttpClient::Preconditions.assert_class('number', number, String)
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs/#{CGI.escape(subcatalog)}/items/#{CGI.escape(number)}").get
              ::Io::Flow::Catalog::V0::Models::Item.new(r)
            end

            # Add subcatalog item
            def post(organization, subcatalog, item_form)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('subcatalog', subcatalog, String)
              HttpClient::Preconditions.assert_class('item_form', item_form, ::Io::Flow::Catalog::V0::Models::ItemForm)
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs/#{CGI.escape(subcatalog)}/items").with_json(item_form.to_json).post
              ::Io::Flow::Catalog::V0::Models::Item.new(r)
            end

            # Update subcatalog item with the specified number, creating if it does not
            # exist.
            def put_by_number(organization, subcatalog, number, item_form)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('subcatalog', subcatalog, String)
              HttpClient::Preconditions.assert_class('number', number, String)
              HttpClient::Preconditions.assert_class('item_form', item_form, ::Io::Flow::Catalog::V0::Models::ItemForm)
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs/#{CGI.escape(subcatalog)}/items/#{CGI.escape(number)}").with_json(item_form.to_json).put
              ::Io::Flow::Catalog::V0::Models::Item.new(r)
            end

            # Delete the subcatalog item with this number
            def delete_by_number(organization, subcatalog, number)
              HttpClient::Preconditions.assert_class('organization', organization, String)
              HttpClient::Preconditions.assert_class('subcatalog', subcatalog, String)
              HttpClient::Preconditions.assert_class('number', number, String)
              r = @client.request("/#{CGI.escape(organization)}/catalog/subcatalogs/#{CGI.escape(subcatalog)}/items/#{CGI.escape(number)}").delete
              nil
            end

          end

        end

        module Models

          # A function can be represented with just it's ID, or the entire model
          class ExpandableFunction

            module Types
              FUNCTION = 'function' unless defined?(FUNCTION)
              FUNCTION_REFERENCE = 'function_reference' unless defined?(FUNCTION_REFERENCE)
            end

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:name], 'ExpandableFunction')
              @name = HttpClient::Preconditions.assert_class('name', opts.delete(:name), String)
            end

            def to_hash
              subtype_to_hash.merge(:discriminator => @name)
            end

            def ExpandableFunction.from_json(hash)
              HttpClient::Preconditions.assert_class('hash', hash, Hash)
              case HttpClient::Helper.symbolize_keys(hash)[:discriminator]
                when Types::FUNCTION; Function.new(hash)
                when Types::FUNCTION_REFERENCE; FunctionReference.new(hash)
                else ExpandableFunctionUndefinedType.new(:name => union_type_name)
              end
            end

          end

          class ExpandableFunctionUndefinedType < ExpandableFunction

            attr_reader :name

            def initialize(incoming={})
              super(:name => 'undefined_type')
              opts = HttpClient::Helper.symbolize_keys(incoming)
              @name = HttpClient::Preconditions.assert_class('name', opts.delete(:name), String)
            end

            def subtype_to_hash
              raise 'Unable to serialize undefined type to json'
            end

            def copy(incoming={})
              raise 'Operation not supported for undefined type'
            end

            def to_hash
              raise 'Operation not supported for undefined type'
            end

          end

          # A subcatalog can be represented with just it's ID, or the entire model
          class ExpandableSubcatalog

            module Types
              SUBCATALOG = 'subcatalog' unless defined?(SUBCATALOG)
              SUBCATALOG_REFERENCE = 'subcatalog_reference' unless defined?(SUBCATALOG_REFERENCE)
            end

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:name], 'ExpandableSubcatalog')
              @name = HttpClient::Preconditions.assert_class('name', opts.delete(:name), String)
            end

            def to_hash
              subtype_to_hash.merge(:discriminator => @name)
            end

            def ExpandableSubcatalog.from_json(hash)
              HttpClient::Preconditions.assert_class('hash', hash, Hash)
              case HttpClient::Helper.symbolize_keys(hash)[:discriminator]
                when Types::SUBCATALOG; Subcatalog.new(hash)
                when Types::SUBCATALOG_REFERENCE; SubcatalogReference.new(hash)
                else ExpandableSubcatalogUndefinedType.new(:name => union_type_name)
              end
            end

          end

          class ExpandableSubcatalogUndefinedType < ExpandableSubcatalog

            attr_reader :name

            def initialize(incoming={})
              super(:name => 'undefined_type')
              opts = HttpClient::Helper.symbolize_keys(incoming)
              @name = HttpClient::Preconditions.assert_class('name', opts.delete(:name), String)
            end

            def subtype_to_hash
              raise 'Unable to serialize undefined type to json'
            end

            def copy(incoming={})
              raise 'Operation not supported for undefined type'
            end

            def to_hash
              raise 'Operation not supported for undefined type'
            end

          end

          class AdjustmentType

            attr_reader :value

            def initialize(value)
              @value = HttpClient::Preconditions.assert_class('value', value, String)
            end

            # Returns the instance of AdjustmentType for this value, creating a new instance for an unknown value
            def AdjustmentType.apply(value)
              if value.instance_of?(AdjustmentType)
                value
              else
                HttpClient::Preconditions.assert_class_or_nil('value', value, String)
                value.nil? ? nil : (from_string(value) || AdjustmentType.new(value))
              end
            end

            # Returns the instance of AdjustmentType for this value, or nil if not found
            def AdjustmentType.from_string(value)
              HttpClient::Preconditions.assert_class('value', value, String)
              AdjustmentType.ALL.find { |v| v.value == value }
            end

            def AdjustmentType.ALL
              @@all ||= [AdjustmentType.fixed_margin, AdjustmentType.percent_margin, AdjustmentType.round]
            end

            def AdjustmentType.fixed_margin
              @@_fixed_margin ||= AdjustmentType.new('fixed_margin')
            end

            def AdjustmentType.percent_margin
              @@_percent_margin ||= AdjustmentType.new('percent_margin')
            end

            def AdjustmentType.round
              @@_round ||= AdjustmentType.new('round')
            end

            def to_hash
              value
            end

          end

          class DeliveredDuty

            attr_reader :value

            def initialize(value)
              @value = HttpClient::Preconditions.assert_class('value', value, String)
            end

            # Returns the instance of DeliveredDuty for this value, creating a new instance for an unknown value
            def DeliveredDuty.apply(value)
              if value.instance_of?(DeliveredDuty)
                value
              else
                HttpClient::Preconditions.assert_class_or_nil('value', value, String)
                value.nil? ? nil : (from_string(value) || DeliveredDuty.new(value))
              end
            end

            # Returns the instance of DeliveredDuty for this value, or nil if not found
            def DeliveredDuty.from_string(value)
              HttpClient::Preconditions.assert_class('value', value, String)
              DeliveredDuty.ALL.find { |v| v.value == value }
            end

            def DeliveredDuty.ALL
              @@all ||= [DeliveredDuty.paid, DeliveredDuty.unpaid]
            end

            def DeliveredDuty.paid
              @@_paid ||= DeliveredDuty.new('paid')
            end

            def DeliveredDuty.unpaid
              @@_unpaid ||= DeliveredDuty.new('unpaid')
            end

            def to_hash
              value
            end

          end

          class Levy

            attr_reader :value

            def initialize(value)
              @value = HttpClient::Preconditions.assert_class('value', value, String)
            end

            # Returns the instance of Levy for this value, creating a new instance for an unknown value
            def Levy.apply(value)
              if value.instance_of?(Levy)
                value
              else
                HttpClient::Preconditions.assert_class_or_nil('value', value, String)
                value.nil? ? nil : (from_string(value) || Levy.new(value))
              end
            end

            # Returns the instance of Levy for this value, or nil if not found
            def Levy.from_string(value)
              HttpClient::Preconditions.assert_class('value', value, String)
              Levy.ALL.find { |v| v.value == value }
            end

            def Levy.ALL
              @@all ||= [Levy.duty, Levy.shipping, Levy.vat]
            end

            def Levy.duty
              @@_duty ||= Levy.new('duty')
            end

            def Levy.shipping
              @@_shipping ||= Levy.new('shipping')
            end

            # Value-Added Tax
            def Levy.vat
              @@_vat ||= Levy.new('vat')
            end

            def to_hash
              value
            end

          end

          class UpdatePolicy

            attr_reader :value

            def initialize(value)
              @value = HttpClient::Preconditions.assert_class('value', value, String)
            end

            # Returns the instance of UpdatePolicy for this value, creating a new instance for an unknown value
            def UpdatePolicy.apply(value)
              if value.instance_of?(UpdatePolicy)
                value
              else
                HttpClient::Preconditions.assert_class_or_nil('value', value, String)
                value.nil? ? nil : (from_string(value) || UpdatePolicy.new(value))
              end
            end

            # Returns the instance of UpdatePolicy for this value, or nil if not found
            def UpdatePolicy.from_string(value)
              HttpClient::Preconditions.assert_class('value', value, String)
              UpdatePolicy.ALL.find { |v| v.value == value }
            end

            def UpdatePolicy.ALL
              @@all ||= [UpdatePolicy.auto, UpdatePolicy.queue, UpdatePolicy.discard]
            end

            def UpdatePolicy.auto
              @@_auto ||= UpdatePolicy.new('auto')
            end

            # Queue item update for approval.
            def UpdatePolicy.queue
              @@_queue ||= UpdatePolicy.new('queue')
            end

            def UpdatePolicy.discard
              @@_discard ||= UpdatePolicy.new('discard')
            end

            def to_hash
              value
            end

          end

          class Adjustment

            attr_reader :name, :value

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:name, :value], 'Adjustment')
              @name = (x = opts.delete(:name); x.is_a?(::Io::Flow::Catalog::V0::Models::AdjustmentType) ? x : ::Io::Flow::Catalog::V0::Models::AdjustmentType.apply(x))
              @value = HttpClient::Preconditions.assert_class('value', opts.delete(:value), Numeric)
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              Adjustment.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :name => name.value,
                :value => value
              }
            end

          end

          class Attribute

            attr_reader :key, :value

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:key, :value], 'Attribute')
              @key = HttpClient::Preconditions.assert_class('key', opts.delete(:key), String)
              @value = HttpClient::Preconditions.assert_class('value', opts.delete(:value), String)
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              Attribute.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :key => key,
                :value => value
              }
            end

          end

          class Catalog

            attr_reader :id

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:id], 'Catalog')
              @id = HttpClient::Preconditions.assert_class('id', opts.delete(:id), String)
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              Catalog.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :id => id
              }
            end

          end

          class CatalogVersion

            attr_reader :id, :timestamp, :type, :catalog

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:id, :timestamp, :type, :catalog], 'CatalogVersion')
              @id = HttpClient::Preconditions.assert_class('id', opts.delete(:id), String)
              @timestamp = HttpClient::Preconditions.assert_class('timestamp', HttpClient::Helper.to_date_time_iso8601(opts.delete(:timestamp)), DateTime)
              @type = (x = opts.delete(:type); x.is_a?(::Io::Flow::Common::V0::Models::ChangeType) ? x : ::Io::Flow::Common::V0::Models::ChangeType.apply(x))
              @catalog = (x = opts.delete(:catalog); x.is_a?(::Io::Flow::Catalog::V0::Models::Catalog) ? x : ::Io::Flow::Catalog::V0::Models::Catalog.new(x))
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              CatalogVersion.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :id => id,
                :timestamp => timestamp,
                :type => type.value,
                :catalog => catalog.to_hash
              }
            end

          end

          # Flow internal model containing an item's origin and classified harmonization
          # code (6 digit)
          class Flow

            attr_reader :origin, :function, :hs6

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              @origin = (x = opts.delete(:origin); x.nil? ? nil : HttpClient::Preconditions.assert_class('origin', x, String))
              @function = (x = opts.delete(:function); x.nil? ? nil : (x = x; x.is_a?(::Io::Flow::Catalog::V0::Models::ExpandableFunction) ? x : ::Io::Flow::Catalog::V0::Models::ExpandableFunction.from_json(x)))
              @hs6 = (x = opts.delete(:hs6); x.nil? ? nil : HttpClient::Preconditions.assert_class('hs6', x, String))
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              Flow.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :origin => origin,
                :function => function.nil? ? nil : function.to_hash,
                :hs6 => hs6
              }
            end

          end

          # Prioritized calculation yielding a localized price (also allows for custom
          # defined price function)
          class Function < ExpandableFunction

            attr_reader :id, :subcatalog_id, :name, :position, :presets, :code, :q

            def initialize(incoming={})
              super(:name => ExpandableFunction::Types::FUNCTION)
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:id, :subcatalog_id, :name, :position, :presets, :code], 'Function')
              @id = HttpClient::Preconditions.assert_class('id', opts.delete(:id), String)
              @subcatalog_id = HttpClient::Preconditions.assert_class('subcatalog_id', opts.delete(:subcatalog_id), String)
              @name = HttpClient::Preconditions.assert_class('name', opts.delete(:name), String)
              @position = HttpClient::Preconditions.assert_class('position', opts.delete(:position), Integer)
              @presets = (x = opts.delete(:presets); x.is_a?(::Io::Flow::Catalog::V0::Models::Presets) ? x : ::Io::Flow::Catalog::V0::Models::Presets.new(x))
              @code = HttpClient::Preconditions.assert_class('code', opts.delete(:code), String)
              @q = (x = opts.delete(:q); x.nil? ? nil : HttpClient::Preconditions.assert_class('q', x, String))
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              Function.new(subtype_to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def subtype_to_hash
              {
                :id => id,
                :subcatalog_id => subcatalog_id,
                :name => name,
                :position => position,
                :presets => presets.to_hash,
                :code => code,
                :q => q
              }
            end

          end

          class FunctionForm

            attr_reader :name, :subcatalog_id, :q, :presets, :code, :position

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:name, :subcatalog_id], 'FunctionForm')
              @name = HttpClient::Preconditions.assert_class('name', opts.delete(:name), String)
              @subcatalog_id = HttpClient::Preconditions.assert_class('subcatalog_id', opts.delete(:subcatalog_id), String)
              @q = (x = opts.delete(:q); x.nil? ? nil : HttpClient::Preconditions.assert_class('q', x, String))
              @presets = (x = opts.delete(:presets); x.nil? ? nil : (x = x; x.is_a?(::Io::Flow::Catalog::V0::Models::Presets) ? x : ::Io::Flow::Catalog::V0::Models::Presets.new(x)))
              @code = (x = opts.delete(:code); x.nil? ? nil : HttpClient::Preconditions.assert_class('code', x, String))
              @position = (x = opts.delete(:position); x.nil? ? nil : HttpClient::Preconditions.assert_class('position', x, Integer))
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              FunctionForm.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :name => name,
                :subcatalog_id => subcatalog_id,
                :q => q,
                :presets => presets.nil? ? nil : presets.to_hash,
                :code => code,
                :position => position
              }
            end

          end

          class FunctionReference < ExpandableFunction

            attr_reader :id

            def initialize(incoming={})
              super(:name => ExpandableFunction::Types::FUNCTION_REFERENCE)
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:id], 'FunctionReference')
              @id = HttpClient::Preconditions.assert_class('id', opts.delete(:id), String)
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              FunctionReference.new(subtype_to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def subtype_to_hash
              {
                :id => id
              }
            end

          end

          class FunctionSummary

            attr_reader :id, :name

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:id, :name], 'FunctionSummary')
              @id = HttpClient::Preconditions.assert_class('id', opts.delete(:id), String)
              @name = HttpClient::Preconditions.assert_class('name', opts.delete(:name), String)
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              FunctionSummary.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :id => id,
                :name => name
              }
            end

          end

          class FunctionVersion

            attr_reader :id, :timestamp, :type, :function

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:id, :timestamp, :type, :function], 'FunctionVersion')
              @id = HttpClient::Preconditions.assert_class('id', opts.delete(:id), String)
              @timestamp = HttpClient::Preconditions.assert_class('timestamp', HttpClient::Helper.to_date_time_iso8601(opts.delete(:timestamp)), DateTime)
              @type = (x = opts.delete(:type); x.is_a?(::Io::Flow::Common::V0::Models::ChangeType) ? x : ::Io::Flow::Common::V0::Models::ChangeType.apply(x))
              @function = (x = opts.delete(:function); x.is_a?(::Io::Flow::Catalog::V0::Models::Function) ? x : ::Io::Flow::Catalog::V0::Models::Function.new(x))
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              FunctionVersion.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :id => id,
                :timestamp => timestamp,
                :type => type.value,
                :function => function.to_hash
              }
            end

          end

          # The URL to an image, with optional tags. Flow Commerce primarily uses images
          # to enhance the administrative tools (e.g. showing an item image in console)
          class Image

            attr_reader :url, :tags

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:url], 'Image')
              @url = HttpClient::Preconditions.assert_class('url', opts.delete(:url), String)
              @tags = HttpClient::Preconditions.assert_class('tags', (x = opts.delete(:tags); x.nil? ? [] : x), Array).map { |v| HttpClient::Preconditions.assert_class('tags', v, String) }
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              Image.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :url => url,
                :tags => tags
              }
            end

          end

          # Image form defines the data needed to create an image
          class ImageForm

            attr_reader :url, :tags

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:url], 'ImageForm')
              @url = HttpClient::Preconditions.assert_class('url', opts.delete(:url), String)
              @tags = (x = opts.delete(:tags); x.nil? ? nil : HttpClient::Preconditions.assert_class('tags', x, Array).map { |v| HttpClient::Preconditions.assert_class('tags', v, String) })
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              ImageForm.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :url => url,
                :tags => tags.nil? ? nil : tags
              }
            end

          end

          # The Flow item defines a specific item that can be purchased by a consumer. For
          # many clients, this will map to a Sku.
          class Item

            attr_reader :id, :number, :locale, :name, :currency, :price, :categories, :description, :attributes, :dimensions, :images, :flow, :local

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:id, :number, :locale, :name, :currency, :price], 'Item')
              @id = HttpClient::Preconditions.assert_class('id', opts.delete(:id), String)
              @number = HttpClient::Preconditions.assert_class('number', opts.delete(:number), String)
              @locale = HttpClient::Preconditions.assert_class('locale', opts.delete(:locale), String)
              @name = HttpClient::Preconditions.assert_class('name', opts.delete(:name), String)
              @currency = HttpClient::Preconditions.assert_class('currency', opts.delete(:currency), String)
              @price = (x = opts.delete(:price); x.is_a?(::Io::Flow::Catalog::V0::Models::Price) ? x : ::Io::Flow::Catalog::V0::Models::Price.new(x))
              @categories = HttpClient::Preconditions.assert_class('categories', (x = opts.delete(:categories); x.nil? ? [] : x), Array).map { |v| HttpClient::Preconditions.assert_class('categories', v, String) }
              @description = (x = opts.delete(:description); x.nil? ? nil : HttpClient::Preconditions.assert_class('description', x, String))
              @attributes = HttpClient::Preconditions.assert_class('attributes', (x = opts.delete(:attributes); x.nil? ? [] : x), Array).map { |v| (x = v; x.is_a?(::Io::Flow::Catalog::V0::Models::Attribute) ? x : ::Io::Flow::Catalog::V0::Models::Attribute.new(x)) }
              @dimensions = HttpClient::Preconditions.assert_class('dimensions', (x = opts.delete(:dimensions); x.nil? ? [] : x), Array).map { |v| (x = v; x.is_a?(::Io::Flow::Common::V0::Models::Dimension) ? x : ::Io::Flow::Common::V0::Models::Dimension.new(x)) }
              @images = HttpClient::Preconditions.assert_class('images', (x = opts.delete(:images); x.nil? ? [] : x), Array).map { |v| (x = v; x.is_a?(::Io::Flow::Catalog::V0::Models::Image) ? x : ::Io::Flow::Catalog::V0::Models::Image.new(x)) }
              @flow = (x = opts.delete(:flow); x.nil? ? nil : (x = x; x.is_a?(::Io::Flow::Catalog::V0::Models::Flow) ? x : ::Io::Flow::Catalog::V0::Models::Flow.new(x)))
              @local = (x = opts.delete(:local); x.nil? ? nil : (x = x; x.is_a?(::Io::Flow::Catalog::V0::Models::Local) ? x : ::Io::Flow::Catalog::V0::Models::Local.new(x)))
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              Item.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :id => id,
                :number => number,
                :locale => locale,
                :name => name,
                :currency => currency,
                :price => price.to_hash,
                :categories => categories,
                :description => description,
                :attributes => attributes.map { |o| o.to_hash },
                :dimensions => dimensions.map { |o| o.to_hash },
                :images => images.map { |o| o.to_hash },
                :flow => flow.nil? ? nil : flow.to_hash,
                :local => local.nil? ? nil : local.to_hash
              }
            end

          end

          # The item form defines the data required to create an item.
          class ItemForm

            attr_reader :number, :locale, :name, :currency, :price, :categories, :description, :attributes, :dimensions, :images

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:number, :locale, :name, :currency, :price], 'ItemForm')
              @number = HttpClient::Preconditions.assert_class('number', opts.delete(:number), String)
              @locale = HttpClient::Preconditions.assert_class('locale', opts.delete(:locale), String)
              @name = HttpClient::Preconditions.assert_class('name', opts.delete(:name), String)
              @currency = HttpClient::Preconditions.assert_class('currency', opts.delete(:currency), String)
              @price = HttpClient::Preconditions.assert_class('price', opts.delete(:price), Numeric)
              @categories = (x = opts.delete(:categories); x.nil? ? nil : HttpClient::Preconditions.assert_class('categories', x, Array).map { |v| HttpClient::Preconditions.assert_class('categories', v, String) })
              @description = (x = opts.delete(:description); x.nil? ? nil : HttpClient::Preconditions.assert_class('description', x, String))
              @attributes = (x = opts.delete(:attributes); x.nil? ? nil : HttpClient::Preconditions.assert_class('attributes', x, Array).map { |v| (x = v; x.is_a?(::Io::Flow::Catalog::V0::Models::Attribute) ? x : ::Io::Flow::Catalog::V0::Models::Attribute.new(x)) })
              @dimensions = (x = opts.delete(:dimensions); x.nil? ? nil : HttpClient::Preconditions.assert_class('dimensions', x, Array).map { |v| (x = v; x.is_a?(::Io::Flow::Common::V0::Models::Dimension) ? x : ::Io::Flow::Common::V0::Models::Dimension.new(x)) })
              @images = (x = opts.delete(:images); x.nil? ? nil : HttpClient::Preconditions.assert_class('images', x, Array).map { |v| (x = v; x.is_a?(::Io::Flow::Catalog::V0::Models::ImageForm) ? x : ::Io::Flow::Catalog::V0::Models::ImageForm.new(x)) })
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              ItemForm.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :number => number,
                :locale => locale,
                :name => name,
                :currency => currency,
                :price => price,
                :categories => categories.nil? ? nil : categories,
                :description => description,
                :attributes => attributes.nil? ? nil : attributes.map { |o| o.to_hash },
                :dimensions => dimensions.nil? ? nil : dimensions.map { |o| o.to_hash },
                :images => images.nil? ? nil : images.map { |o| o.to_hash }
              }
            end

          end

          class ItemVersion

            attr_reader :id, :timestamp, :type, :item

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:id, :timestamp, :type, :item], 'ItemVersion')
              @id = HttpClient::Preconditions.assert_class('id', opts.delete(:id), String)
              @timestamp = HttpClient::Preconditions.assert_class('timestamp', HttpClient::Helper.to_date_time_iso8601(opts.delete(:timestamp)), DateTime)
              @type = (x = opts.delete(:type); x.is_a?(::Io::Flow::Common::V0::Models::ChangeType) ? x : ::Io::Flow::Common::V0::Models::ChangeType.apply(x))
              @item = (x = opts.delete(:item); x.is_a?(::Io::Flow::Catalog::V0::Models::Item) ? x : ::Io::Flow::Catalog::V0::Models::Item.new(x))
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              ItemVersion.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :id => id,
                :timestamp => timestamp,
                :type => type.value,
                :item => item.to_hash
              }
            end

          end

          class Local

            attr_reader :prices

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:prices], 'Local')
              @prices = HttpClient::Preconditions.assert_class('prices', opts.delete(:prices), Array).map { |v| (x = v; x.is_a?(::Io::Flow::Catalog::V0::Models::LocalizedPrice) ? x : ::Io::Flow::Catalog::V0::Models::LocalizedPrice.new(x)) }
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              Local.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :prices => prices.map { |o| o.to_hash }
              }
            end

          end

          class LocalizedPrice

            attr_reader :key, :currency, :amount, :label

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:key, :currency, :amount, :label], 'LocalizedPrice')
              @key = HttpClient::Preconditions.assert_class('key', opts.delete(:key), String)
              @currency = HttpClient::Preconditions.assert_class('currency', opts.delete(:currency), String)
              @amount = HttpClient::Preconditions.assert_class('amount', opts.delete(:amount), Numeric)
              @label = HttpClient::Preconditions.assert_class('label', opts.delete(:label), String)
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              LocalizedPrice.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :key => key,
                :currency => currency,
                :amount => amount,
                :label => label
              }
            end

          end

          # Presentation for UI that is used to generate a localized price function
          class Presets

            attr_reader :adjustments, :levies

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              @adjustments = HttpClient::Preconditions.assert_class('adjustments', (x = opts.delete(:adjustments); x.nil? ? [] : x), Array).map { |v| (x = v; x.is_a?(::Io::Flow::Catalog::V0::Models::Adjustment) ? x : ::Io::Flow::Catalog::V0::Models::Adjustment.new(x)) }
              @levies = HttpClient::Preconditions.assert_class('levies', (x = opts.delete(:levies); x.nil? ? [] : x), Array).map { |v| (x = v; x.is_a?(::Io::Flow::Catalog::V0::Models::Levy) ? x : ::Io::Flow::Catalog::V0::Models::Levy.apply(x)) }
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              Presets.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :adjustments => adjustments.map { |o| o.to_hash },
                :levies => levies.map { |o| o.value }
              }
            end

          end

          class Price

            attr_reader :amount, :label

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:amount, :label], 'Price')
              @amount = HttpClient::Preconditions.assert_class('amount', opts.delete(:amount), Numeric)
              @label = HttpClient::Preconditions.assert_class('label', opts.delete(:label), String)
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              Price.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :amount => amount,
                :label => label
              }
            end

          end

          # A configuration with custom query to select a subset of master catalog items
          # for a localized experience
          class Subcatalog < ExpandableSubcatalog

            attr_reader :id, :catalog, :country, :key, :settings, :query

            def initialize(incoming={})
              super(:name => ExpandableSubcatalog::Types::SUBCATALOG)
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:id, :catalog, :country, :key, :settings], 'Subcatalog')
              @id = HttpClient::Preconditions.assert_class('id', opts.delete(:id), String)
              @catalog = (x = opts.delete(:catalog); x.is_a?(::Io::Flow::Catalog::V0::Models::Catalog) ? x : ::Io::Flow::Catalog::V0::Models::Catalog.new(x))
              @country = HttpClient::Preconditions.assert_class('country', opts.delete(:country), String)
              @key = HttpClient::Preconditions.assert_class('key', opts.delete(:key), String)
              @settings = (x = opts.delete(:settings); x.is_a?(::Io::Flow::Catalog::V0::Models::SubcatalogSettings) ? x : ::Io::Flow::Catalog::V0::Models::SubcatalogSettings.new(x))
              @query = (x = opts.delete(:query); x.nil? ? nil : HttpClient::Preconditions.assert_class('query', x, String))
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              Subcatalog.new(subtype_to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def subtype_to_hash
              {
                :id => id,
                :catalog => catalog.to_hash,
                :country => country,
                :key => key,
                :settings => settings.to_hash,
                :query => query
              }
            end

          end

          class SubcatalogForm

            attr_reader :country, :key, :query, :settings

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:country], 'SubcatalogForm')
              @country = HttpClient::Preconditions.assert_class('country', opts.delete(:country), String)
              @key = (x = opts.delete(:key); x.nil? ? nil : HttpClient::Preconditions.assert_class('key', x, String))
              @query = (x = opts.delete(:query); x.nil? ? nil : HttpClient::Preconditions.assert_class('query', x, String))
              @settings = (x = opts.delete(:settings); x.nil? ? nil : (x = x; x.is_a?(::Io::Flow::Catalog::V0::Models::SubcatalogSettingsForm) ? x : ::Io::Flow::Catalog::V0::Models::SubcatalogSettingsForm.new(x)))
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              SubcatalogForm.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :country => country,
                :key => key,
                :query => query,
                :settings => settings.nil? ? nil : settings.to_hash
              }
            end

          end

          class SubcatalogItem

            attr_reader :id

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:id], 'SubcatalogItem')
              @id = HttpClient::Preconditions.assert_class('id', opts.delete(:id), String)
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              SubcatalogItem.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :id => id
              }
            end

          end

          class SubcatalogReference < ExpandableSubcatalog

            attr_reader :id

            def initialize(incoming={})
              super(:name => ExpandableSubcatalog::Types::SUBCATALOG_REFERENCE)
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:id], 'SubcatalogReference')
              @id = HttpClient::Preconditions.assert_class('id', opts.delete(:id), String)
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              SubcatalogReference.new(subtype_to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def subtype_to_hash
              {
                :id => id
              }
            end

          end

          class SubcatalogSettings

            attr_reader :update_policy

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              @update_policy = (x = (x = opts.delete(:update_policy); x.nil? ? "auto" : x); x.is_a?(::Io::Flow::Catalog::V0::Models::UpdatePolicy) ? x : ::Io::Flow::Catalog::V0::Models::UpdatePolicy.apply(x))
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              SubcatalogSettings.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :update_policy => update_policy.value
              }
            end

          end

          class SubcatalogSettingsForm

            attr_reader :update_policy

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              @update_policy = (x = opts.delete(:update_policy); x.nil? ? nil : (x = x; x.is_a?(::Io::Flow::Catalog::V0::Models::UpdatePolicy) ? x : ::Io::Flow::Catalog::V0::Models::UpdatePolicy.apply(x)))
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              SubcatalogSettingsForm.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :update_policy => update_policy.nil? ? nil : update_policy.value
              }
            end

          end

          class SubcatalogVersion

            attr_reader :id, :timestamp, :type, :subcatalog

            def initialize(incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              HttpClient::Preconditions.require_keys(opts, [:id, :timestamp, :type, :subcatalog], 'SubcatalogVersion')
              @id = HttpClient::Preconditions.assert_class('id', opts.delete(:id), String)
              @timestamp = HttpClient::Preconditions.assert_class('timestamp', HttpClient::Helper.to_date_time_iso8601(opts.delete(:timestamp)), DateTime)
              @type = (x = opts.delete(:type); x.is_a?(::Io::Flow::Common::V0::Models::ChangeType) ? x : ::Io::Flow::Common::V0::Models::ChangeType.apply(x))
              @subcatalog = (x = opts.delete(:subcatalog); x.is_a?(::Io::Flow::Catalog::V0::Models::Subcatalog) ? x : ::Io::Flow::Catalog::V0::Models::Subcatalog.new(x))
            end

            def to_json
              JSON.dump(to_hash)
            end

            def copy(incoming={})
              SubcatalogVersion.new(to_hash.merge(HttpClient::Helper.symbolize_keys(incoming)))
            end

            def to_hash
              {
                :id => id,
                :timestamp => timestamp,
                :type => type.value,
                :subcatalog => subcatalog.to_hash
              }
            end

          end

        end

        # ===== END OF SERVICE DEFINITION =====
        module HttpClient

          class Request

            def initialize(uri)
              @uri = Preconditions.assert_class('uri', uri, URI)
              @params = nil
              @body = nil
              @auth = nil
              @headers = {}
              @header_keys_lower_case = []
            end

            def with_header(name, value)
              Preconditions.check_not_blank('name', name, "Header name is required")
              Preconditions.check_not_blank('value', value, "Header value is required")
              Preconditions.check_state(!@headers.has_key?(name),
                                        "Duplicate header named[%s]" % name)
              @headers[name] = value
              @header_keys_lower_case << name.downcase
              self
            end

            def with_auth(auth)
              Preconditions.assert_class('auth', auth, HttpClient::Authorization)
              Preconditions.check_state(@auth.nil?, "auth previously set")

              if auth.scheme.name == AuthScheme::BASIC.name
                @auth = auth
              else
                raise "Auth Scheme[#{auth.scheme.name}] not supported"
              end
              self
            end

            def with_query(params)
              Preconditions.assert_class('params', params, Hash)
              Preconditions.check_state(@params.nil?, "Already have query parameters")
              @params = params
              self
            end

            # Wrapper to set Content-Type header to application/json and set
            # the provided json document as the body
            def with_json(json)
              @headers['Content-Type'] ||= 'application/json; charset=UTF-8'
              with_body(json)
            end

            def with_body(body)
              Preconditions.check_not_blank('body', body)
              @body = body
              self
            end

            # Creates a new Net:HTTP client. The client returned should be
            # fully configured to make a request.
            def new_http_client
              client = Net::HTTP.new(@uri.host, @uri.port)
              if @uri.scheme == "https"
                configure_ssl(client)
              end
              client
            end

            # If HTTPS is required, this method accepts an HTTP Client and configures SSL
            def configure_ssl(http)
              Preconditions.assert_class('http', http, Net::HTTP)
              http.use_ssl = true
              http.verify_mode = OpenSSL::SSL::VERIFY_PEER
              http.cert_store = OpenSSL::X509::Store.new
              http.cert_store.set_default_paths
            end

            def get(&block)
              do_request(Net::HTTP::Get, &block)
            end

            def delete(&block)
              do_request(Net::HTTP::Delete, &block)
            end

            def options(&block)
              do_request(Net::HTTP::Options, &block)
            end

            def post(&block)
              do_request(Net::HTTP::Post, &block)
            end

            def put(&block)
              do_request(Net::HTTP::Put, &block)
            end

            class PATCH < Net::HTTP::Put
              METHOD = "PATCH"
            end

            def patch(&block)
              do_request(PATCH, &block)
            end

            def do_request(klass)
              Preconditions.assert_class('klass', klass, Class)

              uri = @uri.to_s
              if q = to_query(@params)
                uri += "?%s" % q
              end

              request = klass.send(:new, uri)

              curl = ['curl']
              if klass != Net::HTTP::Get
                curl << "-X%s" % klass.name.split("::").last.upcase
              end

              if @body
                # DEBUG path = "/tmp/rest_client.tmp"
                # DEBUG File.open(path, "w") { |os| os << @body.to_s }
                # DEBUG curl << "-d@%s" % path
                request.body = @body
              end

              if @auth
                curl << "-u \"%s:%s\"" % [@auth.username, @auth.password]
                Preconditions.check_state(!@header_keys_lower_case.include?("authorization"),
                                          "Cannot specify both an Authorization header and an auth instance")
                user_pass = "%s:%s" % [@auth.username, @auth.password]
                encoded = Base64.encode64(user_pass).to_s.split("\n").map(&:strip).join
                request.add_field("Authorization", "Basic %s" % encoded)
              end

              @headers.each { |key, value|
                curl <<  "-H \"%s: %s\"" % [key, value]
                request.add_field(key, value)
              }

              curl << "'%s'" % uri
              # DEBUG puts curl.join(" ")

              raw_response = http_request(request)
              response = raw_response.to_s == "" ? nil : JSON.parse(raw_response)

              if block_given?
                yield response
              else
                response
              end
            end

            private
            def to_query(params={})
              parts = (params || {}).map { |k,v|
                if v.respond_to?(:each)
                  v.map { |el| "%s=%s" % [k, CGI.escape(el.to_s)] }
                else
                  "%s=%s" % [k, CGI.escape(v.to_s)]
                end
              }
              parts.empty? ? nil : parts.join("&")
            end

            def http_request(request)
              response = begin
                           new_http_client.request(request)
                         rescue SocketError => e
                           raise Exception.new("Error accessing uri[#{@uri}]: #{e}")
                         end

              case response
              when Net::HTTPSuccess
                response.body
              else
                body = response.body rescue nil
                raise HttpClient::ServerError.new(response.code.to_i, response.message, :body => body, :uri => @uri.to_s)
              end
            end
          end

          class ServerError < StandardError

            attr_reader :code, :details, :body, :uri

            def initialize(code, details, incoming={})
              opts = HttpClient::Helper.symbolize_keys(incoming)
              @code = HttpClient::Preconditions.assert_class('code', code, Integer)
              @details = HttpClient::Preconditions.assert_class('details', details, String)
              @body = HttpClient::Preconditions.assert_class_or_nil('body', opts.delete(:body), String)
              @uri = HttpClient::Preconditions.assert_class_or_nil('uri', opts.delete(:uri), String)
              HttpClient::Preconditions.assert_empty_opts(opts)
              super(self.message)
            end

            def message
              m = "%s %s" % [@code, @details]
              if @body
                m << ": %s" % @body
              end
              m
            end

            def body_json
              JSON.parse(@body)
            end

          end

          class PreconditionException < Exception

            attr_reader :message

            def initialize(message)
              super(message)
              @message = message
            end

          end

          module Preconditions

            def Preconditions.check_argument(expression, error_message=nil)
              if !expression
                raise PreconditionException.new(error_message || "check_argument failed")
              end
              nil
            end

            def Preconditions.check_state(expression, error_message=nil)
              if !expression
                raise PreconditionException.new(error_message || "check_state failed")
              end
              nil
            end

            def Preconditions.check_not_nil(field_name, reference, error_message=nil)
              if reference.nil?
                raise PreconditionException.new(error_message || "argument for %s cannot be nil" % field_name)
              end
              reference
            end

            def Preconditions.check_not_blank(field_name, reference, error_message=nil)
              if reference.to_s.strip == ""
                raise PreconditionException.new(error_message || "argument for %s cannot be blank" % field_name)
              end
              reference
            end

            # Throws an error if opts is not empty. Useful when parsing
            # arguments to a function
            def Preconditions.assert_empty_opts(opts)
              if !opts.empty?
                raise PreconditionException.new("Invalid opts: #{opts.keys.inspect}\n#{opts.inspect}")
              end
            end

            # Requires that the provided hash has the specified keys.
            # @param fields A list of symbols
            def Preconditions.require_keys(hash, fields, error_prefix=nil)
              missing = fields.select { |f| !hash.has_key?(f) }
              if !missing.empty?
                msg = "Missing required fields: " + missing.join(", ")
                raise PreconditionException.new(error_prefix.empty? ? msg : "#{error_prefix}: #{msg}")
              end
            end

            # Asserts that value is not nill and is_?(klass). Returns
            # value. Common use is
            #
            # amount = Preconditions.assert_class('amount', amount, BigDecimal)
            def Preconditions.assert_class(field_name, value, klass)
              Preconditions.check_not_nil('field_name', field_name)
              Preconditions.check_not_nil('klass', klass)
              Preconditions.check_not_nil('value', value, "Value for %s cannot be nil. Expected an instance of class %s" % [field_name, klass.name])
              Preconditions.check_state(value.is_a?(klass),
                                        "Value for #{field_name} is of type[#{value.class}] - class[#{klass}] is required. value[#{value.inspect.to_s}]")
              value
            end

            def Preconditions.assert_class_or_nil(field_name, value, klass)
              if !value.nil?
                Preconditions.assert_class(field_name, value, klass)
              end
            end

            def Preconditions.assert_boolean(field_name, value)
              Preconditions.check_not_nil('field_name', field_name)
              Preconditions.check_not_nil('value', value, "Value for %s cannot be nil. Expected an instance of TrueClass or FalseClass" % field_name)
              Preconditions.check_state(value.is_a?(TrueClass) || value.is_a?(FalseClass),
                                        "Value for #{field_name} is of type[#{value.class}] - class[TrueClass or FalseClass] is required. value[#{value.inspect.to_s}]")
              value
            end

            def Preconditions.assert_boolean_or_nil(field_name, value)
              if !value.nil?
                Preconditions.assert_boolean(field_name, value)
              end
            end

            def Preconditions.assert_collection_of_class(field_name, values, klass)
              Preconditions.assert_class(field_name, values, Array)
              values.each { |v| Preconditions.assert_class(field_name, v, klass) }
            end

            def Preconditions.assert_hash_of_class(field_name, hash, klass)
              Preconditions.assert_class(field_name, hash, Hash)
              values.each { |k, v| Preconditions.assert_class(field_name, v, klass) }
            end

          end

          class AuthScheme

            attr_reader :name

            def initialize(name)
              @name = HttpClient::Preconditions.check_not_blank('name', name)
            end

            BASIC = AuthScheme.new("basic") unless defined?(BASIC)

          end

          class Authorization

            attr_reader :scheme, :username, :password

            def initialize(scheme, username, opts={})
              @scheme = HttpClient::Preconditions.assert_class('schema', scheme, AuthScheme)
              @username = HttpClient::Preconditions.check_not_blank('username', username, "username is required")
              @password = HttpClient::Preconditions.assert_class_or_nil('password', opts.delete(:password), String)
              HttpClient::Preconditions.assert_empty_opts(opts)
            end

            def Authorization.basic(username, password=nil)
              Authorization.new(AuthScheme::BASIC, username, :password => password)
            end

          end

          module Helper

            def Helper.symbolize_keys(hash)
              Preconditions.assert_class('hash', hash, Hash)
              new_hash = {}
              hash.each { |k, v|
                new_hash[k.to_sym] = v
              }
              new_hash
            end

            def Helper.to_big_decimal(value)
              value ? BigDecimal.new(value.to_s) : nil
            end

            def Helper.to_object(value)
              value ? JSON.parse(value) : nil
            end

            def Helper.to_uuid(value)
              Preconditions.check_state(value.nil? || value.match(/^\w\w\w\w\w\w\w\w\-\w\w\w\w\-\w\w\w\w\-\w\w\w\w\-\w\w\w\w\w\w\w\w\w\w\w\w$/),
                                        "Invalid guid[%s]" % value)
              value
            end

            def Helper.to_date_iso8601(value)
              if value.is_a?(Date)
                value
              elsif value
                Date.parse(value.to_s)
              else
                nil
              end
            end

            def Helper.to_date_time_iso8601(value)
              if value.is_a?(DateTime)
                value
              elsif value
                DateTime.parse(value.to_s)
              else
                nil
              end
            end

            def Helper.date_iso8601_to_string(value)
              value.nil? ? nil : value.strftime('%Y-%m-%d')
            end

            def Helper.date_time_iso8601_to_string(value)
              value.nil? ? nil : value.strftime('%Y-%m-%dT%H:%M:%S%z')
            end

            TRUE_STRINGS = ['t', 'true', 'y', 'yes', 'on', '1', 'trueclass'] unless defined?(TRUE_STRINGS)
            FALSE_STRINGS = ['f', 'false', 'n', 'no', 'off', '0', 'falseclass'] unless defined?(FALSE_STRINGS)

            def Helper.to_boolean(field_name, value)
              string = value.to_s.strip.downcase
              if TRUE_STRINGS.include?(string)
                true
              elsif FALSE_STRINGS.include?(string)
                false
              elsif string != ""
                raise PreconditionException.new("Unsupported boolean value[#{string}]. For true, must be one of: #{TRUE_STRINGS.inspect}. For false, must be one of: #{FALSE_STRINGS.inspect}")
              else
                nil
              end
            end

          end

        end
      end
    end
  end
end